project:
  type: website

website:
  title: "Toronto EEB Student Journal Club"
  navbar:
    background: primary
    search: true
    left:
      - text: "Schedule"
        file: index.qmd
  repo-url: https://github.com/metekaanyuksel/eeb-student-journal-club.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full